---
- name: Get info for FA
  hosts: localhost
  gather_facts: true
  collections:
  - purestorage.flasharray
  vars_files:
  - testdrive_vars.yaml
  tasks:
    - name: Get flasharray info
      purefa_info:
        fa_url: "{{ fa1_ip }}"
        api_token: "{{ fa1_token }}"
      register: fa1_info
    - name: show info
      debug:
        msg: "{{ fa1_info['purefa_info']['default'] }}"
